Adventure game rearranged into classes
Agata-Gizinska/Adventure_game pull request #1
Opened 2022-02-10 09:53 UTC by Agata-Gizinska

Adventure game refreshed version - created classes Player, Room (parent class), child classes: DarkRoom, MonsterRoom, Stairs, Prison, Basement; created game engine

2022-03-03 18:09 UTC, czarnadzuma11 requested changes

2022-03-03 18:09 UTC, czarnadzuma11 commented on adventure_game.py
> +        self._next_room = DarkRoom()  # create DarkRoom as initial room
Add initial_room=DarkRoom() paramter to __init__  and change this line to 
```self._next_room = initial_room```

2022-03-03 18:09 UTC, czarnadzuma11 commented on adventure_game.py
> +        choice = int(input('Go left (1) or right (2)?'))
choice should keep asking the user for input until user provides an acceptable value. Create a function
```
def user_choice(prompt, choices):
  while True:
    choice = input(f'{prompt} {choices}')
    if choice in choices:
      return choice
```
and use it to ask for input, don't worry about types. Just use strings since you decide what those values are anyway

for example
```
choice = user_choice(prompt='Go left(1) or right(2)', ['1', '2']])
if choice == '1':
...
```

2022-03-03 18:09 UTC, czarnadzuma11 commented on adventure_game.py
> +        first_choice_ = str(input('Use stairs (yes/no)?'))
Give it a different name instead of suffixing with _, applies to the whole review

2022-03-04 11:11 UTC, Agata-Gizinska commented on adventure_game.py
> +        self._next_room = DarkRoom()  # create DarkRoom as initial room
This solution throws an error:
Traceback (most recent call last):
  File "C:\Users\User\adventure_game.py", line 4, in <module>
    class Player:
  File "C:\Users\User\adventure_game.py", line 10, in Player
    def __init__(self, name='Nameless', initial_room=DarkRoom()):
NameError: name 'DarkRoom' is not defined

2022-03-04 13:02 UTC, Agata-Gizinska commented on adventure_game.py
> +        choice = int(input('Go left (1) or right (2)?'))
ok

2022-03-04 13:12 UTC, Agata-Gizinska commented on adventure_game.py
> +        first_choice_ = str(input('Use stairs (yes/no)?'))
ok

2022-04-03 11:08 UTC, czarnadzuma11 commented on adventure_game.py
> +        self._next_room = DarkRoom()  # create DarkRoom as initial room
Then modify the code for it to not throw an error, during code review you are usually presented with ideas for a suggested solution and are responsible to make it work. It's fine if you do not know how to address the issue but you should explain what you tried and request further instruction.

This happens because 
def __init__(..
gets evaluated when interpreter is reading the file and DarkRoom is not defined yet, interpreter needs it right now and we define it later down the file.

while 

self._next_room = DarkRoom()
gets evaluated later, when we actually start executing the function


One solution to such situation is to arrange the code in the order of dependency
class Room:
...
class DarkRoom: # below Room because it needs room to define itself
...
class Player: # below DarkRoom because it needs DarkRoom
...

but then we will run into another issue since Room class needs Player to be defined!
This in turn could be fixed by removing _player : Player type hint, which while may be nice is not critical and introduces a troublesome dependency.

The same is true for my previous idea of 
def init(self, name='Nameless', initial_room=DarkRoom()):
Rooms and players are not related in nature

What i think would be best to do is
1) remove room class name references in player class
2) remove player class name references in room class
3) make initial_room a required paramtere without default value. This way we will need to have all of the rooms and all of the players defined only when we will acutally need them, which currently is in main()

2022-04-12 09:49 UTC, Agata-Gizinska commented on adventure_game.py
> +        self._next_room = DarkRoom()  # create DarkRoom as initial room
done

2022-04-20 19:32 UTC, czarnadzuma11 approved these changes

2022-04-21 06:11 UTC, merged